export const bonus_data = {
  H1: [
    {
      month: 1,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 2,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 3,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 4,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 5,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 6,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
  ],
  H2: [
    {
      month: 7,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 8,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 9,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 10,
      sales: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 11,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
    {
      month: 12,
      sales: "",
      sales_area: "",
      sales_amount: "",
      sales_area_amount: "",
      quota: "10000",
    },
  ],
};



export const result_data = (type) => {
  if (type === "H1") {
    return [
      {
        title: "1月",
        value: 1,
        total: "8,400",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "8,400" },
          { type: "当月封顶后实发绩效奖", value: "8,400" },
        ],
      },
      {
        title: "2月",
        value: 2,
        total: "18,000",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "18,000" },
          { type: "当月封顶后实发绩效奖", value: "18,000" },
        ],
      },
      {
        title: "3月",
        value: 3,
        total: "15,123",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "15,123" },
          { type: "当月封顶后实发绩效奖", value: "15,123" },
        ],
      },
      {
        title: "4月",
        value: 4,
        total: "25,000",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "27,000" },
          { type: "当月封顶后实发绩效奖", value: "25,000" },
        ],
      },
      {
        title: "5月",
        value: 5,
        total: "25,000",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "30,000" },
          { type: "当月封顶后实发绩效奖", value: "25,000" },
        ],
      },
      {
        title: "6月",
        value: 6,
        total: "19,370",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "19,370" },
          { type: "当月封顶后实发绩效奖", value: "19,370" },
        ],
      },
    ];
  } else {
    return [
      {
        title: "7月",
        value: 7,
        total: "8,400",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "8,400" },
          { type: "当月封顶后实发绩效奖", value: "8,400" },
        ],
      },
      {
        title: "8月",
        value: 8,
        total: "18,000",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "18,000" },
          { type: "当月封顶后实发绩效奖", value: "18,000" },
        ],
      },
      {
        title: "9月",
        value: 9,
        total: "15,123",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "15,123" },
          { type: "当月封顶后实发绩效奖", value: "15,123" },
        ],
      },
      {
        title: "10月",
        value: 10,
        total: "25,000",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "27,000" },
          { type: "当月封顶后实发绩效奖", value: "25,000" },
        ],
      },
      {
        title: "11月",
        value: 11,
        total: "25,000",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "30,000" },
          { type: "当月封顶后实发绩效奖", value: "25,000" },
        ],
      },
      {
        title: "12月",
        value: 12,
        total: "19,370",
        table: [
          { type: "YTD达成率", value: "25,000" },
          { type: "YTD达成奖", value: "30,000" },
          { type: "YTD贡献奖", value: "30,000" },
          { type: "YTD已发绩效奖", value: "1,000" },
          { type: "当月应发绩效奖", value: "19,370" },
          { type: "当月封顶后实发绩效奖", value: "19,370" },
        ],
      },
    ];
  }
};
